# compose for nginx
version: "3.9"

services: 
    cms1:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        image: ghcr.io/REPOSITORY/IMAGE:latest
        ports:
            - "8080:80"
        environment: 
            - NGINX_PORT=80
